"""add_exchange_rate_table

Revision ID: 1f696405f822
Revises: 5a713a60d8a3
Create Date: 2026-04-12 18:22:57.167382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f696405f822'
down_revision: Union[str, Sequence[str], None] = '5a713a60d8a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('rate_to_uah', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency')
    )
    op.create_index(op.f('ix_exchange_rate_id'), 'exchange_rate', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exchange_rate_id'), table_name='exchange_rate')
    op.drop_table('exchange_rate')
    # ### end Alembic commands ###
