"""add preferred_currency

Revision ID: 365c34c0233c
Revises: 1f696405f822
Create Date: 2026-04-12 19:30:44.997057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '365c34c0233c'
down_revision: Union[str, Sequence[str], None] = '1f696405f822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('rate_to_uah', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency')
    )
    op.create_index(op.f('ix_exchange_rate_id'), 'exchange_rate', ['id'], unique=False)
    op.alter_column('subscriptions', 'name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('subscriptions', 'category',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('subscriptions', 'default_price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.create_index(op.f('ix_subscriptions_name'), 'subscriptions', ['name'], unique=False)
    op.add_column('user_preferences', sa.Column('preferred_currency', sa.String(length=10), nullable=True))
    op.alter_column('user_subscriptions', 'billing_cycle',
               existing_type=mysql.ENUM('monthly', 'yearly'),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_subscriptions', 'billing_cycle',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('monthly', 'yearly'),
               existing_nullable=True)
    op.drop_column('user_preferences', 'preferred_currency')
    op.drop_index(op.f('ix_subscriptions_name'), table_name='subscriptions')
    op.alter_column('subscriptions', 'default_price',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('subscriptions', 'category',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('subscriptions', 'name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_exchange_rate_id'), table_name='exchange_rate')
    op.drop_table('exchange_rate')
    # ### end Alembic commands ###
