"""sync_user_subscriptions

Revision ID: 5a713a60d8a3
Revises: 1f2e3d4c5b6a
Create Date: 2026-03-31 18:41:52.866479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5a713a60d8a3'
down_revision: Union[str, Sequence[str], None] = '1f2e3d4c5b6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('subscriptions', 'category',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('subscriptions', 'default_price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.drop_index(op.f('ix_subscriptions_category'), table_name='subscriptions')
    op.alter_column('user_subscriptions', 'billing_cycle',
               existing_type=mysql.ENUM('monthly', 'yearly'),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_subscriptions', 'billing_cycle',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('monthly', 'yearly'),
               existing_nullable=True)
    op.create_index(op.f('ix_subscriptions_category'), 'subscriptions', ['category'], unique=False)
    op.alter_column('subscriptions', 'default_price',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('subscriptions', 'category',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('subscriptions', 'name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
